# Generated by Django 3.2 on 2021-10-12 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batalhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('continente', models.CharField(choices=[('AMS', 'América do Sul'), ('AMC', 'América Central'), ('AMN', 'América do Norte'), ('AFR', 'África'), ('EUR', 'Europa'), ('ASI', 'Ásia'), ('OCE', 'Oceania')], max_length=3)),
                ('tamanho', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=0, max_digits=3)),
                ('altura', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(choices=[('SOL', 'Soldado'), ('CAB', 'Cabo'), ('SAR', 'Sargento'), ('SUB', 'Subtenente'), ('TEN', 'Tenente'), ('CAP', 'Capitão'), ('MAJ', 'Major'), ('COR', 'Coronel'), ('GEN', 'General')], max_length=255)),
                ('ano_ingresso', models.DateField(verbose_name='Ano de Ingresso')),
                ('batalhao_atual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exercito.batalhao', verbose_name='Batalhão')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercito.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Exercito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lema', models.CharField(max_length=255)),
                ('ano_fundacao', models.DateField()),
                ('pais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercito.pais', verbose_name='País')),
            ],
        ),
        migrations.AddField(
            model_name='batalhao',
            name='comandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercito.militar'),
        ),
        migrations.AddField(
            model_name='batalhao',
            name='exercito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercito.exercito', verbose_name='Exército'),
        ),
    ]
